### ISSUE TITLE
Add installation instructions in README

### ISSUE THREAD

**Issue by maxxer** [imanudin11/zimbra-ui#1]
I know it's always up to date [on your blog](https://imanudin.net/2019/08/21/how-to-install-zimbra-universal-ui/), but for consistency it would be useful here as well :)

**Comment by imanudin11** [comment]
> I know it's always up to date [on your blog](https://imanudin.net/2019/08/21/how-to-install-zimbra-universal-ui/), but for consistency it would be useful here as well :)

Hello Maxxer,
Thanks for your attention. You right. I should be writing in README also :) . I usually save supplement file that needs on this Github as free repository :)

**Comment by imanudin11** [comment]
> I know it's always up to date [on your blog](https://imanudin.net/2019/08/21/how-to-install-zimbra-universal-ui/), but for consistency it would be useful here as well :)

Done. I've updated the README
